FROM comfyui:cu128

WORKDIR /opt/DiffSynth-Studio

COPY extern/DiffSynth-Studio/ /opt/DiffSynth-Studio/

RUN python -m pip install --no-cache-dir -e .
RUN python -m pip install --no-cache-dir bitsandbytes

RUN groupadd -g 1102 app && useradd -u 1091 -g app -m -s /bin/bash app
